apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.appName }}-pod
  labels:
    app: {{ .Values.appName }}
spec:
  hostNetwork: false
  securityContext:
    runAsNonRoot: true
  containers:
    - name: helper
      image: busybox
      command: ["sh","-c","sleep 3600"]
