apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-svc
  labels:
    app: {{ .Values.appName }}
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
    - port: 80
      targetPort: 80
