apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  namespace: dev-test
  labels:
    app: demo
spec:
  containers:
    - name: app
      image: nginx
      resources: {}
    - name: sidecar
      image: busybox
      # resources:
      #   limits:
      #     cpu: "50m"
      #     memory: "64Mi"
