apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  labels:
    app: demo
spec:
  containers:
    - name: worker
      image: alpine
      command: ["sh","-c","sleep 3600"]
      # no securityContext → triggers RunAsNonRoot and Missing SecurityContext
